### ISSUE TITLE
Add timeouts and an enable/disable switch

### ISSUE THREAD

**Issue by jordan-brough** [solidusio/solidus_avatax#15]
We need to add timeouts and an enable/disable switch to solidus_avatax. (Avatax had an outage on Black Friday that caused us some pain.)

We want to be able to flip the disable switch or change the timeout length without having to restart our app.

Some options I can think of:
1. Turn the existing SpreeAvatax::Config class into an ActiveRecord model and store these preferences in there.
2. Add "preferences" to `Spree::TaxRate`:

``` ruby
class Spree::TaxRate
  preference :avatax_enabled, :boolean, default: true
  preference :avatax_timeout_seconds, :integer, default: 20
end
```

I think I prefer option 1. Option 2 feels a bit invasive to me.  Any other recommendations or thoughts?

**Comment by jhawthorn** [comment]
Another option is to make `SpreeAvatax::Config` could be an `AppConfiguration`, like `Spree::Config` or `Spree::Frontend::Config` etc. Which would allow it to be configured in the database or in memory (via `use_static_preferences!`)

**Comment by athal7** [comment]
One other option to consider is to put a setting in the preferences column for the SpreeAvatax::Calculator, which could be made administerable through the tax rate settings admin

**Comment by jordan-brough** [comment]
@jhawthorn interesting, thanks.  Where would be the right place to store that in the database?  I'm still wrapping my brain around the preferences system.  I'd like to store it in the database so that the preference is shared across all servers and can be updated instantaneously and without restarting the app.  Would the Spree::Preference model be the right place to put it?  Looking through Solidus I get the feeling that that model [is deprecated](https://github.com/solidusio/solidus/blob/ec065a3f124d4bffca677a12d4c708e0e69c9d9e/core/app/models/spree/preferences/configuration.rb#L40) in some way...?

@athal7 good point, I didn't think of that, thanks. It feels a little strange to me to put those things on the Calculator though. I think I might prefer one of the other options first personally.

@jhawthorn @athal7 - Another thought I just had is that it might be nice to have an append-only spree_avatax_configs table in the database (and always read from the most recent row) since that would give us a audit log of config changes.  Any thoughts on that as well?

**Comment by athal7** [comment]
@jordan-brough I'd be on board with your last suggestion or with @jhawthorn's suggestion

**Comment by jordan-brough** [comment]
@athal7 cool, thanks.

@athal7 @jhawthorn here's the kind of thing I'm thinking for that last suggestion: https://gist.github.com/jordan-brough/687285f847a9755cb840

Plus following up with adding an admin UI for changing the value. Lmk what you guys think.

**Comment by jordan-brough** [comment]
@athal7 @jhawthorn I've opened a PR for that last suggestion. See https://github.com/solidusio/solidus_avatax/issues/15. Lmk what you think. Thanks.

**Comment by tvdeyen** [comment]
@jordan-brough @jhawthorn is this issue still valid?
