### ISSUE TITLE
Rename "generate" methods

### ISSUE THREAD

**Issue by jordan-brough** [solidusio/solidus_avatax#7]
See discussion [here](https://github.com/solidusio/solidus_avatax/pull/6/files#r36635283).

It's surprising that [`SpreeAvatax::SalesInvoice.generate(order)`](https://github.com/solidusio/solidus_avatax/blob/647b1bf749868a8ba9a73c1338cc1c4599805d93/app/models/spree_avatax/sales_invoice.rb#L23) modifies the order, rather than just creating an invoice.  Something like `SpreeAvatax::SalesInvoice.calculate_and_set_taxes(order)` would probably be a better name.

There are at least three `generate` methods defined in solidus_avatax right now. We'd probably want to update all of them and deprecate the `generate` name.

**Comment by gmacdougall** [comment]
Thanks for filing an issue for this.
